<h1>Free Rent Rider</h1>
<p>On <strong>{if $contract_info->signing}{$contract_info->date_signing|date_format:'%b %e, %Y'}{else}{$smarty.now|date_format:'%b %e, %Y'}{/if}</strong> by and between {$landlord->name} (hereinafter “Owner”), owner of the premises known as and located at {$contract_info->rental_address} (“subject premises”) and <strong>{foreach $contract_users as $user}{if $contract_user->id != $user->id}{$user->name|escape}, {/if}{/foreach}{$contract_user->name|escape}</strong> (hereinafter “Tenants”), tenants of <strong>{$apartment->name}</strong> in the subject premises (hereinafter “subject apartment”) as follows:</p>
<ol>
	<li>The parties agree that the monthly rent for the subject apartment is <strong>{$contract_info->price_month|convert} (US Dollars)</strong> per month, as set forth in the Lease (hereinafter the “Lease”), for the entire lease term commencing on <strong>{$contract_info->date_from|date}</strong> and expiring on <strong>{$contract_info->date_to|date}</strong>.</li>
	<li>As part of the lease agreement the Landlord agrees to abate <strong>{$contract_info->free_rental_amount|convert} (US Dollars)</strong> of rent which will be spread over the course of the fourteen month lease term, which will result in a <strong>{$discount_per_month|convert} (US Dollars)</strong> monthly rent credit issued for the duration of the lease term as stated above. All rent credit and abatements are subject to the tenants signing and the Landlord executing a lease from <strong>{$contract_info->date_from|date}</strong> to <strong>{$contract_info->date_to|date}</strong> after the signing of this Free Rent Rider.</li>
	<li>Said temporary concession is neither intended as a permanent rent reduction, nor is it intended as a preference to govern throughout Tenants’ tenancy. Other than during the period specified at 1 and 2 of this Rider, the full monthly legal regulated rent recited in this Lease, or a preferential rent if offered, or any renewals thereof, subject to future lawful adjustments (if any), must be paid in order to satisfy Tenants’ rent obligation pursuant to the lease then in effect. It is acknowledged and agreed by the parties that the legal regulated rent for any subsequent lease renewal will be based upon the legal regulated rent set forth in 1 of this Rider, subject to any lawful adjustments, such that the owner’s willingness and agreement to grant a temporary concession have no effect upon the normal market rent.</li>
	<li>The parties shall be deemed to have jointly drawn this Rider in order to avoid any negative inference against the preparer of the document. The covenants, agreements, terms, provisions and conditions contained in this Rider shall be binding upon and inure to the benefit of the parties hereto and their respective successors and assigns.</li>
</ol>
<p><strong>IN WITNESS WHEREOF</strong>, the parties hereto have caused this Agreement to be executed as of the day and year first above written.</p>
